# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/predator/Documents/Project/temp/libcouchbase

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/predator/Documents/Project/temp/libcouchbase

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/predator/Documents/Project/temp/libcouchbase/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all:
	@./tools/build.sh 1200 "sample"
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named couchbaseS

# Build rule for target.
couchbaseS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 couchbaseS
.PHONY : couchbaseS

# fast build rule for target.
couchbaseS/fast:
	$(MAKE) -f CMakeFiles/couchbaseS.dir/build.make CMakeFiles/couchbaseS.dir/build
.PHONY : couchbaseS/fast

#=============================================================================
# Target rules for targets named mcreq

# Build rule for target.
mcreq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcreq
.PHONY : mcreq

# fast build rule for target.
mcreq/fast:
	$(MAKE) -f CMakeFiles/mcreq.dir/build.make CMakeFiles/mcreq.dir/build
.PHONY : mcreq/fast

#=============================================================================
# Target rules for targets named couchbase_utils

# Build rule for target.
couchbase_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 couchbase_utils
.PHONY : couchbase_utils

# fast build rule for target.
couchbase_utils/fast:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/build
.PHONY : couchbase_utils/fast

#=============================================================================
# Target rules for targets named lcbio-cxx

# Build rule for target.
lcbio-cxx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcbio-cxx
.PHONY : lcbio-cxx

# fast build rule for target.
lcbio-cxx/fast:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/build
.PHONY : lcbio-cxx/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named netbuf

# Build rule for target.
netbuf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 netbuf
.PHONY : netbuf

# fast build rule for target.
netbuf/fast:
	$(MAKE) -f CMakeFiles/netbuf.dir/build.make CMakeFiles/netbuf.dir/build
.PHONY : netbuf/fast

#=============================================================================
# Target rules for targets named mcreq-cxx

# Build rule for target.
mcreq-cxx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcreq-cxx
.PHONY : mcreq-cxx

# fast build rule for target.
mcreq-cxx/fast:
	$(MAKE) -f CMakeFiles/mcreq-cxx.dir/build.make CMakeFiles/mcreq-cxx.dir/build
.PHONY : mcreq-cxx/fast

#=============================================================================
# Target rules for targets named netbuf-malloc

# Build rule for target.
netbuf-malloc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 netbuf-malloc
.PHONY : netbuf-malloc

# fast build rule for target.
netbuf-malloc/fast:
	$(MAKE) -f CMakeFiles/netbuf-malloc.dir/build.make CMakeFiles/netbuf-malloc.dir/build
.PHONY : netbuf-malloc/fast

#=============================================================================
# Target rules for targets named lcbcore

# Build rule for target.
lcbcore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcbcore
.PHONY : lcbcore

# fast build rule for target.
lcbcore/fast:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/build
.PHONY : lcbcore/fast

#=============================================================================
# Target rules for targets named lcbcore-cxx

# Build rule for target.
lcbcore-cxx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcbcore-cxx
.PHONY : lcbcore-cxx

# fast build rule for target.
lcbcore-cxx/fast:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/build
.PHONY : lcbcore-cxx/fast

#=============================================================================
# Target rules for targets named lcb_jsparse

# Build rule for target.
lcb_jsparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcb_jsparse
.PHONY : lcb_jsparse

# fast build rule for target.
lcb_jsparse/fast:
	$(MAKE) -f CMakeFiles/lcb_jsparse.dir/build.make CMakeFiles/lcb_jsparse.dir/build
.PHONY : lcb_jsparse/fast

#=============================================================================
# Target rules for targets named couchbase

# Build rule for target.
couchbase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 couchbase
.PHONY : couchbase

# fast build rule for target.
couchbase/fast:
	$(MAKE) -f CMakeFiles/couchbase.dir/build.make CMakeFiles/couchbase.dir/build
.PHONY : couchbase/fast

#=============================================================================
# Target rules for targets named rdb

# Build rule for target.
rdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rdb
.PHONY : rdb

# fast build rule for target.
rdb/fast:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/build
.PHONY : rdb/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named file_manifest

# Build rule for target.
file_manifest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_manifest
.PHONY : file_manifest

# fast build rule for target.
file_manifest/fast:
	$(MAKE) -f CMakeFiles/file_manifest.dir/build.make CMakeFiles/file_manifest.dir/build
.PHONY : file_manifest/fast

#=============================================================================
# Target rules for targets named lcbio

# Build rule for target.
lcbio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcbio
.PHONY : lcbio

# fast build rule for target.
lcbio/fast:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/build
.PHONY : lcbio/fast

#=============================================================================
# Target rules for targets named lcbht

# Build rule for target.
lcbht: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcbht
.PHONY : lcbht

# fast build rule for target.
lcbht/fast:
	$(MAKE) -f CMakeFiles/lcbht.dir/build.make CMakeFiles/lcbht.dir/build
.PHONY : lcbht/fast

#=============================================================================
# Target rules for targets named vbucket

# Build rule for target.
vbucket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vbucket
.PHONY : vbucket

# fast build rule for target.
vbucket/fast:
	$(MAKE) -f src/vbucket/CMakeFiles/vbucket.dir/build.make src/vbucket/CMakeFiles/vbucket.dir/build
.PHONY : vbucket/fast

#=============================================================================
# Target rules for targets named cbsasl

# Build rule for target.
cbsasl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cbsasl
.PHONY : cbsasl

# fast build rule for target.
cbsasl/fast:
	$(MAKE) -f contrib/cbsasl/CMakeFiles/cbsasl.dir/build.make contrib/cbsasl/CMakeFiles/cbsasl.dir/build
.PHONY : cbsasl/fast

#=============================================================================
# Target rules for targets named cliopts

# Build rule for target.
cliopts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cliopts
.PHONY : cliopts

# fast build rule for target.
cliopts/fast:
	$(MAKE) -f contrib/cliopts/CMakeFiles/cliopts.dir/build.make contrib/cliopts/CMakeFiles/cliopts.dir/build
.PHONY : cliopts/fast

#=============================================================================
# Target rules for targets named lcbssl

# Build rule for target.
lcbssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcbssl
.PHONY : lcbssl

# fast build rule for target.
lcbssl/fast:
	$(MAKE) -f src/ssl/CMakeFiles/lcbssl.dir/build.make src/ssl/CMakeFiles/lcbssl.dir/build
.PHONY : lcbssl/fast

#=============================================================================
# Target rules for targets named lcb_jsoncpp

# Build rule for target.
lcb_jsoncpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcb_jsoncpp
.PHONY : lcb_jsoncpp

# fast build rule for target.
lcb_jsoncpp/fast:
	$(MAKE) -f contrib/lcb-jsoncpp/CMakeFiles/lcb_jsoncpp.dir/build.make contrib/lcb-jsoncpp/CMakeFiles/lcb_jsoncpp.dir/build
.PHONY : lcb_jsoncpp/fast

#=============================================================================
# Target rules for targets named lcb_snappy

# Build rule for target.
lcb_snappy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcb_snappy
.PHONY : lcb_snappy

# fast build rule for target.
lcb_snappy/fast:
	$(MAKE) -f contrib/snappy/CMakeFiles/lcb_snappy.dir/build.make contrib/snappy/CMakeFiles/lcb_snappy.dir/build
.PHONY : lcb_snappy/fast

#=============================================================================
# Target rules for targets named alltests

# Build rule for target.
alltests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alltests
.PHONY : alltests

# fast build rule for target.
alltests/fast:
	$(MAKE) -f tests/CMakeFiles/alltests.dir/build.make tests/CMakeFiles/alltests.dir/build
.PHONY : alltests/fast

#=============================================================================
# Target rules for targets named unit-tests

# Build rule for target.
unit-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit-tests
.PHONY : unit-tests

# fast build rule for target.
unit-tests/fast:
	$(MAKE) -f tests/CMakeFiles/unit-tests.dir/build.make tests/CMakeFiles/unit-tests.dir/build
.PHONY : unit-tests/fast

#=============================================================================
# Target rules for targets named mocksupport

# Build rule for target.
mocksupport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mocksupport
.PHONY : mocksupport

# fast build rule for target.
mocksupport/fast:
	$(MAKE) -f tests/CMakeFiles/mocksupport.dir/build.make tests/CMakeFiles/mocksupport.dir/build
.PHONY : mocksupport/fast

#=============================================================================
# Target rules for targets named mc-tests

# Build rule for target.
mc-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mc-tests
.PHONY : mc-tests

# fast build rule for target.
mc-tests/fast:
	$(MAKE) -f tests/CMakeFiles/mc-tests.dir/build.make tests/CMakeFiles/mc-tests.dir/build
.PHONY : mc-tests/fast

#=============================================================================
# Target rules for targets named nonio-tests

# Build rule for target.
nonio-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nonio-tests
.PHONY : nonio-tests

# fast build rule for target.
nonio-tests/fast:
	$(MAKE) -f tests/CMakeFiles/nonio-tests.dir/build.make tests/CMakeFiles/nonio-tests.dir/build
.PHONY : nonio-tests/fast

#=============================================================================
# Target rules for targets named check-all

# Build rule for target.
check-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-all
.PHONY : check-all

# fast build rule for target.
check-all/fast:
	$(MAKE) -f tests/CMakeFiles/check-all.dir/build.make tests/CMakeFiles/check-all.dir/build
.PHONY : check-all/fast

#=============================================================================
# Target rules for targets named ioserver

# Build rule for target.
ioserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ioserver
.PHONY : ioserver

# fast build rule for target.
ioserver/fast:
	$(MAKE) -f tests/CMakeFiles/ioserver.dir/build.make tests/CMakeFiles/ioserver.dir/build
.PHONY : ioserver/fast

#=============================================================================
# Target rules for targets named mc-malloc-tests

# Build rule for target.
mc-malloc-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mc-malloc-tests
.PHONY : mc-malloc-tests

# fast build rule for target.
mc-malloc-tests/fast:
	$(MAKE) -f tests/CMakeFiles/mc-malloc-tests.dir/build.make tests/CMakeFiles/mc-malloc-tests.dir/build
.PHONY : mc-malloc-tests/fast

#=============================================================================
# Target rules for targets named netbuf-tests

# Build rule for target.
netbuf-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 netbuf-tests
.PHONY : netbuf-tests

# fast build rule for target.
netbuf-tests/fast:
	$(MAKE) -f tests/CMakeFiles/netbuf-tests.dir/build.make tests/CMakeFiles/netbuf-tests.dir/build
.PHONY : netbuf-tests/fast

#=============================================================================
# Target rules for targets named sock-tests

# Build rule for target.
sock-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sock-tests
.PHONY : sock-tests

# fast build rule for target.
sock-tests/fast:
	$(MAKE) -f tests/CMakeFiles/sock-tests.dir/build.make tests/CMakeFiles/sock-tests.dir/build
.PHONY : sock-tests/fast

#=============================================================================
# Target rules for targets named rdb-tests

# Build rule for target.
rdb-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rdb-tests
.PHONY : rdb-tests

# fast build rule for target.
rdb-tests/fast:
	$(MAKE) -f tests/CMakeFiles/rdb-tests.dir/build.make tests/CMakeFiles/rdb-tests.dir/build
.PHONY : rdb-tests/fast

#=============================================================================
# Target rules for targets named vbucket-tests

# Build rule for target.
vbucket-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vbucket-tests
.PHONY : vbucket-tests

# fast build rule for target.
vbucket-tests/fast:
	$(MAKE) -f tests/CMakeFiles/vbucket-tests.dir/build.make tests/CMakeFiles/vbucket-tests.dir/build
.PHONY : vbucket-tests/fast

#=============================================================================
# Target rules for targets named htparse-tests

# Build rule for target.
htparse-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 htparse-tests
.PHONY : htparse-tests

# fast build rule for target.
htparse-tests/fast:
	$(MAKE) -f tests/CMakeFiles/htparse-tests.dir/build.make tests/CMakeFiles/htparse-tests.dir/build
.PHONY : htparse-tests/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f tests/gtest/CMakeFiles/gtest.dir/build.make tests/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f tests/gtest/CMakeFiles/gtest_main.dir/build.make tests/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named cbc-n1qlback

# Build rule for target.
cbc-n1qlback: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cbc-n1qlback
.PHONY : cbc-n1qlback

# fast build rule for target.
cbc-n1qlback/fast:
	$(MAKE) -f tools/CMakeFiles/cbc-n1qlback.dir/build.make tools/CMakeFiles/cbc-n1qlback.dir/build
.PHONY : cbc-n1qlback/fast

#=============================================================================
# Target rules for targets named cbc-pillowfight

# Build rule for target.
cbc-pillowfight: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cbc-pillowfight
.PHONY : cbc-pillowfight

# fast build rule for target.
cbc-pillowfight/fast:
	$(MAKE) -f tools/CMakeFiles/cbc-pillowfight.dir/build.make tools/CMakeFiles/cbc-pillowfight.dir/build
.PHONY : cbc-pillowfight/fast

#=============================================================================
# Target rules for targets named linenoise

# Build rule for target.
linenoise: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linenoise
.PHONY : linenoise

# fast build rule for target.
linenoise/fast:
	$(MAKE) -f tools/CMakeFiles/linenoise.dir/build.make tools/CMakeFiles/linenoise.dir/build
.PHONY : linenoise/fast

#=============================================================================
# Target rules for targets named cbc

# Build rule for target.
cbc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cbc
.PHONY : cbc

# fast build rule for target.
cbc/fast:
	$(MAKE) -f tools/CMakeFiles/cbc.dir/build.make tools/CMakeFiles/cbc.dir/build
.PHONY : cbc/fast

#=============================================================================
# Target rules for targets named lcbtools

# Build rule for target.
lcbtools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcbtools
.PHONY : lcbtools

# fast build rule for target.
lcbtools/fast:
	$(MAKE) -f tools/CMakeFiles/lcbtools.dir/build.make tools/CMakeFiles/lcbtools.dir/build
.PHONY : lcbtools/fast

#=============================================================================
# Target rules for targets named cbc-subdoc

# Build rule for target.
cbc-subdoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cbc-subdoc
.PHONY : cbc-subdoc

# fast build rule for target.
cbc-subdoc/fast:
	$(MAKE) -f tools/CMakeFiles/cbc-subdoc.dir/build.make tools/CMakeFiles/cbc-subdoc.dir/build
.PHONY : cbc-subdoc/fast

#=============================================================================
# Target rules for targets named couchbase_select

# Build rule for target.
couchbase_select: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 couchbase_select
.PHONY : couchbase_select

# fast build rule for target.
couchbase_select/fast:
	$(MAKE) -f plugins/io/select/CMakeFiles/couchbase_select.dir/build.make plugins/io/select/CMakeFiles/couchbase_select.dir/build
.PHONY : couchbase_select/fast

contrib/genhash/genhash.o: contrib/genhash/genhash.c.o

.PHONY : contrib/genhash/genhash.o

# target to build an object file
contrib/genhash/genhash.c.o:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/contrib/genhash/genhash.c.o
.PHONY : contrib/genhash/genhash.c.o

contrib/genhash/genhash.i: contrib/genhash/genhash.c.i

.PHONY : contrib/genhash/genhash.i

# target to preprocess a source file
contrib/genhash/genhash.c.i:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/contrib/genhash/genhash.c.i
.PHONY : contrib/genhash/genhash.c.i

contrib/genhash/genhash.s: contrib/genhash/genhash.c.s

.PHONY : contrib/genhash/genhash.s

# target to generate assembly for a file
contrib/genhash/genhash.c.s:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/contrib/genhash/genhash.c.s
.PHONY : contrib/genhash/genhash.c.s

contrib/http_parser/http_parser.o: contrib/http_parser/http_parser.c.o

.PHONY : contrib/http_parser/http_parser.o

# target to build an object file
contrib/http_parser/http_parser.c.o:
	$(MAKE) -f CMakeFiles/lcbht.dir/build.make CMakeFiles/lcbht.dir/contrib/http_parser/http_parser.c.o
.PHONY : contrib/http_parser/http_parser.c.o

contrib/http_parser/http_parser.i: contrib/http_parser/http_parser.c.i

.PHONY : contrib/http_parser/http_parser.i

# target to preprocess a source file
contrib/http_parser/http_parser.c.i:
	$(MAKE) -f CMakeFiles/lcbht.dir/build.make CMakeFiles/lcbht.dir/contrib/http_parser/http_parser.c.i
.PHONY : contrib/http_parser/http_parser.c.i

contrib/http_parser/http_parser.s: contrib/http_parser/http_parser.c.s

.PHONY : contrib/http_parser/http_parser.s

# target to generate assembly for a file
contrib/http_parser/http_parser.c.s:
	$(MAKE) -f CMakeFiles/lcbht.dir/build.make CMakeFiles/lcbht.dir/contrib/http_parser/http_parser.c.s
.PHONY : contrib/http_parser/http_parser.c.s

src/auth.o: src/auth.cc.o

.PHONY : src/auth.o

# target to build an object file
src/auth.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/auth.cc.o
.PHONY : src/auth.cc.o

src/auth.i: src/auth.cc.i

.PHONY : src/auth.i

# target to preprocess a source file
src/auth.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/auth.cc.i
.PHONY : src/auth.cc.i

src/auth.s: src/auth.cc.s

.PHONY : src/auth.s

# target to generate assembly for a file
src/auth.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/auth.cc.s
.PHONY : src/auth.cc.s

src/bootstrap.o: src/bootstrap.cc.o

.PHONY : src/bootstrap.o

# target to build an object file
src/bootstrap.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bootstrap.cc.o
.PHONY : src/bootstrap.cc.o

src/bootstrap.i: src/bootstrap.cc.i

.PHONY : src/bootstrap.i

# target to preprocess a source file
src/bootstrap.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bootstrap.cc.i
.PHONY : src/bootstrap.cc.i

src/bootstrap.s: src/bootstrap.cc.s

.PHONY : src/bootstrap.s

# target to generate assembly for a file
src/bootstrap.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bootstrap.cc.s
.PHONY : src/bootstrap.cc.s

src/bucketconfig/bc_cccp.o: src/bucketconfig/bc_cccp.cc.o

.PHONY : src/bucketconfig/bc_cccp.o

# target to build an object file
src/bucketconfig/bc_cccp.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_cccp.cc.o
.PHONY : src/bucketconfig/bc_cccp.cc.o

src/bucketconfig/bc_cccp.i: src/bucketconfig/bc_cccp.cc.i

.PHONY : src/bucketconfig/bc_cccp.i

# target to preprocess a source file
src/bucketconfig/bc_cccp.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_cccp.cc.i
.PHONY : src/bucketconfig/bc_cccp.cc.i

src/bucketconfig/bc_cccp.s: src/bucketconfig/bc_cccp.cc.s

.PHONY : src/bucketconfig/bc_cccp.s

# target to generate assembly for a file
src/bucketconfig/bc_cccp.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_cccp.cc.s
.PHONY : src/bucketconfig/bc_cccp.cc.s

src/bucketconfig/bc_file.o: src/bucketconfig/bc_file.cc.o

.PHONY : src/bucketconfig/bc_file.o

# target to build an object file
src/bucketconfig/bc_file.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_file.cc.o
.PHONY : src/bucketconfig/bc_file.cc.o

src/bucketconfig/bc_file.i: src/bucketconfig/bc_file.cc.i

.PHONY : src/bucketconfig/bc_file.i

# target to preprocess a source file
src/bucketconfig/bc_file.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_file.cc.i
.PHONY : src/bucketconfig/bc_file.cc.i

src/bucketconfig/bc_file.s: src/bucketconfig/bc_file.cc.s

.PHONY : src/bucketconfig/bc_file.s

# target to generate assembly for a file
src/bucketconfig/bc_file.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_file.cc.s
.PHONY : src/bucketconfig/bc_file.cc.s

src/bucketconfig/bc_http.o: src/bucketconfig/bc_http.cc.o

.PHONY : src/bucketconfig/bc_http.o

# target to build an object file
src/bucketconfig/bc_http.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_http.cc.o
.PHONY : src/bucketconfig/bc_http.cc.o

src/bucketconfig/bc_http.i: src/bucketconfig/bc_http.cc.i

.PHONY : src/bucketconfig/bc_http.i

# target to preprocess a source file
src/bucketconfig/bc_http.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_http.cc.i
.PHONY : src/bucketconfig/bc_http.cc.i

src/bucketconfig/bc_http.s: src/bucketconfig/bc_http.cc.s

.PHONY : src/bucketconfig/bc_http.s

# target to generate assembly for a file
src/bucketconfig/bc_http.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_http.cc.s
.PHONY : src/bucketconfig/bc_http.cc.s

src/bucketconfig/bc_static.o: src/bucketconfig/bc_static.cc.o

.PHONY : src/bucketconfig/bc_static.o

# target to build an object file
src/bucketconfig/bc_static.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_static.cc.o
.PHONY : src/bucketconfig/bc_static.cc.o

src/bucketconfig/bc_static.i: src/bucketconfig/bc_static.cc.i

.PHONY : src/bucketconfig/bc_static.i

# target to preprocess a source file
src/bucketconfig/bc_static.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_static.cc.i
.PHONY : src/bucketconfig/bc_static.cc.i

src/bucketconfig/bc_static.s: src/bucketconfig/bc_static.cc.s

.PHONY : src/bucketconfig/bc_static.s

# target to generate assembly for a file
src/bucketconfig/bc_static.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/bc_static.cc.s
.PHONY : src/bucketconfig/bc_static.cc.s

src/bucketconfig/confmon.o: src/bucketconfig/confmon.cc.o

.PHONY : src/bucketconfig/confmon.o

# target to build an object file
src/bucketconfig/confmon.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/confmon.cc.o
.PHONY : src/bucketconfig/confmon.cc.o

src/bucketconfig/confmon.i: src/bucketconfig/confmon.cc.i

.PHONY : src/bucketconfig/confmon.i

# target to preprocess a source file
src/bucketconfig/confmon.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/confmon.cc.i
.PHONY : src/bucketconfig/confmon.cc.i

src/bucketconfig/confmon.s: src/bucketconfig/confmon.cc.s

.PHONY : src/bucketconfig/confmon.s

# target to generate assembly for a file
src/bucketconfig/confmon.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/bucketconfig/confmon.cc.s
.PHONY : src/bucketconfig/confmon.cc.s

src/callbacks.o: src/callbacks.c.o

.PHONY : src/callbacks.o

# target to build an object file
src/callbacks.c.o:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/callbacks.c.o
.PHONY : src/callbacks.c.o

src/callbacks.i: src/callbacks.c.i

.PHONY : src/callbacks.i

# target to preprocess a source file
src/callbacks.c.i:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/callbacks.c.i
.PHONY : src/callbacks.c.i

src/callbacks.s: src/callbacks.c.s

.PHONY : src/callbacks.s

# target to generate assembly for a file
src/callbacks.c.s:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/callbacks.c.s
.PHONY : src/callbacks.c.s

src/cbft.o: src/cbft.cc.o

.PHONY : src/cbft.o

# target to build an object file
src/cbft.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/cbft.cc.o
.PHONY : src/cbft.cc.o

src/cbft.i: src/cbft.cc.i

.PHONY : src/cbft.i

# target to preprocess a source file
src/cbft.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/cbft.cc.i
.PHONY : src/cbft.cc.i

src/cbft.s: src/cbft.cc.s

.PHONY : src/cbft.s

# target to generate assembly for a file
src/cbft.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/cbft.cc.s
.PHONY : src/cbft.cc.s

src/cntl.o: src/cntl.cc.o

.PHONY : src/cntl.o

# target to build an object file
src/cntl.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/cntl.cc.o
.PHONY : src/cntl.cc.o

src/cntl.i: src/cntl.cc.i

.PHONY : src/cntl.i

# target to preprocess a source file
src/cntl.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/cntl.cc.i
.PHONY : src/cntl.cc.i

src/cntl.s: src/cntl.cc.s

.PHONY : src/cntl.s

# target to generate assembly for a file
src/cntl.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/cntl.cc.s
.PHONY : src/cntl.cc.s

src/connspec.o: src/connspec.cc.o

.PHONY : src/connspec.o

# target to build an object file
src/connspec.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/connspec.cc.o
.PHONY : src/connspec.cc.o

src/connspec.i: src/connspec.cc.i

.PHONY : src/connspec.i

# target to preprocess a source file
src/connspec.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/connspec.cc.i
.PHONY : src/connspec.cc.i

src/connspec.s: src/connspec.cc.s

.PHONY : src/connspec.s

# target to generate assembly for a file
src/connspec.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/connspec.cc.s
.PHONY : src/connspec.cc.s

src/crypto.o: src/crypto.cc.o

.PHONY : src/crypto.o

# target to build an object file
src/crypto.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/crypto.cc.o
.PHONY : src/crypto.cc.o

src/crypto.i: src/crypto.cc.i

.PHONY : src/crypto.i

# target to preprocess a source file
src/crypto.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/crypto.cc.i
.PHONY : src/crypto.cc.i

src/crypto.s: src/crypto.cc.s

.PHONY : src/crypto.s

# target to generate assembly for a file
src/crypto.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/crypto.cc.s
.PHONY : src/crypto.cc.s

src/dns-srv.o: src/dns-srv.cc.o

.PHONY : src/dns-srv.o

# target to build an object file
src/dns-srv.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/dns-srv.cc.o
.PHONY : src/dns-srv.cc.o

src/dns-srv.i: src/dns-srv.cc.i

.PHONY : src/dns-srv.i

# target to preprocess a source file
src/dns-srv.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/dns-srv.cc.i
.PHONY : src/dns-srv.cc.i

src/dns-srv.s: src/dns-srv.cc.s

.PHONY : src/dns-srv.s

# target to generate assembly for a file
src/dns-srv.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/dns-srv.cc.s
.PHONY : src/dns-srv.cc.s

src/dump.o: src/dump.cc.o

.PHONY : src/dump.o

# target to build an object file
src/dump.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/dump.cc.o
.PHONY : src/dump.cc.o

src/dump.i: src/dump.cc.i

.PHONY : src/dump.i

# target to preprocess a source file
src/dump.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/dump.cc.i
.PHONY : src/dump.cc.i

src/dump.s: src/dump.cc.s

.PHONY : src/dump.s

# target to generate assembly for a file
src/dump.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/dump.cc.s
.PHONY : src/dump.cc.s

src/errmap.o: src/errmap.cc.o

.PHONY : src/errmap.o

# target to build an object file
src/errmap.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/errmap.cc.o
.PHONY : src/errmap.cc.o

src/errmap.i: src/errmap.cc.i

.PHONY : src/errmap.i

# target to preprocess a source file
src/errmap.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/errmap.cc.i
.PHONY : src/errmap.cc.i

src/errmap.s: src/errmap.cc.s

.PHONY : src/errmap.s

# target to generate assembly for a file
src/errmap.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/errmap.cc.s
.PHONY : src/errmap.cc.s

src/getconfig.o: src/getconfig.cc.o

.PHONY : src/getconfig.o

# target to build an object file
src/getconfig.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/getconfig.cc.o
.PHONY : src/getconfig.cc.o

src/getconfig.i: src/getconfig.cc.i

.PHONY : src/getconfig.i

# target to preprocess a source file
src/getconfig.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/getconfig.cc.i
.PHONY : src/getconfig.cc.i

src/getconfig.s: src/getconfig.cc.s

.PHONY : src/getconfig.s

# target to generate assembly for a file
src/getconfig.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/getconfig.cc.s
.PHONY : src/getconfig.cc.s

src/gethrtime.o: src/gethrtime.c.o

.PHONY : src/gethrtime.o

# target to build an object file
src/gethrtime.c.o:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/gethrtime.c.o
.PHONY : src/gethrtime.c.o

src/gethrtime.i: src/gethrtime.c.i

.PHONY : src/gethrtime.i

# target to preprocess a source file
src/gethrtime.c.i:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/gethrtime.c.i
.PHONY : src/gethrtime.c.i

src/gethrtime.s: src/gethrtime.c.s

.PHONY : src/gethrtime.s

# target to generate assembly for a file
src/gethrtime.c.s:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/gethrtime.c.s
.PHONY : src/gethrtime.c.s

src/handler.o: src/handler.cc.o

.PHONY : src/handler.o

# target to build an object file
src/handler.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/handler.cc.o
.PHONY : src/handler.cc.o

src/handler.i: src/handler.cc.i

.PHONY : src/handler.i

# target to preprocess a source file
src/handler.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/handler.cc.i
.PHONY : src/handler.cc.i

src/handler.s: src/handler.cc.s

.PHONY : src/handler.s

# target to generate assembly for a file
src/handler.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/handler.cc.s
.PHONY : src/handler.cc.s

src/hashtable.o: src/hashtable.c.o

.PHONY : src/hashtable.o

# target to build an object file
src/hashtable.c.o:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/hashtable.c.o
.PHONY : src/hashtable.c.o

src/hashtable.i: src/hashtable.c.i

.PHONY : src/hashtable.i

# target to preprocess a source file
src/hashtable.c.i:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/hashtable.c.i
.PHONY : src/hashtable.c.i

src/hashtable.s: src/hashtable.c.s

.PHONY : src/hashtable.s

# target to generate assembly for a file
src/hashtable.c.s:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/hashtable.c.s
.PHONY : src/hashtable.c.s

src/hostlist.o: src/hostlist.cc.o

.PHONY : src/hostlist.o

# target to build an object file
src/hostlist.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/hostlist.cc.o
.PHONY : src/hostlist.cc.o

src/hostlist.i: src/hostlist.cc.i

.PHONY : src/hostlist.i

# target to preprocess a source file
src/hostlist.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/hostlist.cc.i
.PHONY : src/hostlist.cc.i

src/hostlist.s: src/hostlist.cc.s

.PHONY : src/hostlist.s

# target to generate assembly for a file
src/hostlist.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/hostlist.cc.s
.PHONY : src/hostlist.cc.s

src/http/http.o: src/http/http.cc.o

.PHONY : src/http/http.o

# target to build an object file
src/http/http.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/http/http.cc.o
.PHONY : src/http/http.cc.o

src/http/http.i: src/http/http.cc.i

.PHONY : src/http/http.i

# target to preprocess a source file
src/http/http.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/http/http.cc.i
.PHONY : src/http/http.cc.i

src/http/http.s: src/http/http.cc.s

.PHONY : src/http/http.s

# target to generate assembly for a file
src/http/http.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/http/http.cc.s
.PHONY : src/http/http.cc.s

src/http/http_io.o: src/http/http_io.cc.o

.PHONY : src/http/http_io.o

# target to build an object file
src/http/http_io.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/http/http_io.cc.o
.PHONY : src/http/http_io.cc.o

src/http/http_io.i: src/http/http_io.cc.i

.PHONY : src/http/http_io.i

# target to preprocess a source file
src/http/http_io.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/http/http_io.cc.i
.PHONY : src/http/http_io.cc.i

src/http/http_io.s: src/http/http_io.cc.s

.PHONY : src/http/http_io.s

# target to generate assembly for a file
src/http/http_io.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/http/http_io.cc.s
.PHONY : src/http/http_io.cc.s

src/instance.o: src/instance.cc.o

.PHONY : src/instance.o

# target to build an object file
src/instance.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/instance.cc.o
.PHONY : src/instance.cc.o

src/instance.i: src/instance.cc.i

.PHONY : src/instance.i

# target to preprocess a source file
src/instance.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/instance.cc.i
.PHONY : src/instance.cc.i

src/instance.s: src/instance.cc.s

.PHONY : src/instance.s

# target to generate assembly for a file
src/instance.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/instance.cc.s
.PHONY : src/instance.cc.s

src/iofactory.o: src/iofactory.c.o

.PHONY : src/iofactory.o

# target to build an object file
src/iofactory.c.o:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/iofactory.c.o
.PHONY : src/iofactory.c.o

src/iofactory.i: src/iofactory.c.i

.PHONY : src/iofactory.i

# target to preprocess a source file
src/iofactory.c.i:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/iofactory.c.i
.PHONY : src/iofactory.c.i

src/iofactory.s: src/iofactory.c.s

.PHONY : src/iofactory.s

# target to generate assembly for a file
src/iofactory.c.s:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/iofactory.c.s
.PHONY : src/iofactory.c.s

src/jsparse/parser.o: src/jsparse/parser.cc.o

.PHONY : src/jsparse/parser.o

# target to build an object file
src/jsparse/parser.cc.o:
	$(MAKE) -f CMakeFiles/lcb_jsparse.dir/build.make CMakeFiles/lcb_jsparse.dir/src/jsparse/parser.cc.o
.PHONY : src/jsparse/parser.cc.o

src/jsparse/parser.i: src/jsparse/parser.cc.i

.PHONY : src/jsparse/parser.i

# target to preprocess a source file
src/jsparse/parser.cc.i:
	$(MAKE) -f CMakeFiles/lcb_jsparse.dir/build.make CMakeFiles/lcb_jsparse.dir/src/jsparse/parser.cc.i
.PHONY : src/jsparse/parser.cc.i

src/jsparse/parser.s: src/jsparse/parser.cc.s

.PHONY : src/jsparse/parser.s

# target to generate assembly for a file
src/jsparse/parser.cc.s:
	$(MAKE) -f CMakeFiles/lcb_jsparse.dir/build.make CMakeFiles/lcb_jsparse.dir/src/jsparse/parser.cc.s
.PHONY : src/jsparse/parser.cc.s

src/lcbht/lcbht.o: src/lcbht/lcbht.cc.o

.PHONY : src/lcbht/lcbht.o

# target to build an object file
src/lcbht/lcbht.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/lcbht/lcbht.cc.o
.PHONY : src/lcbht/lcbht.cc.o

src/lcbht/lcbht.i: src/lcbht/lcbht.cc.i

.PHONY : src/lcbht/lcbht.i

# target to preprocess a source file
src/lcbht/lcbht.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/lcbht/lcbht.cc.i
.PHONY : src/lcbht/lcbht.cc.i

src/lcbht/lcbht.s: src/lcbht/lcbht.cc.s

.PHONY : src/lcbht/lcbht.s

# target to generate assembly for a file
src/lcbht/lcbht.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/lcbht/lcbht.cc.s
.PHONY : src/lcbht/lcbht.cc.s

src/lcbio/connect.o: src/lcbio/connect.cc.o

.PHONY : src/lcbio/connect.o

# target to build an object file
src/lcbio/connect.cc.o:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/src/lcbio/connect.cc.o
.PHONY : src/lcbio/connect.cc.o

src/lcbio/connect.i: src/lcbio/connect.cc.i

.PHONY : src/lcbio/connect.i

# target to preprocess a source file
src/lcbio/connect.cc.i:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/src/lcbio/connect.cc.i
.PHONY : src/lcbio/connect.cc.i

src/lcbio/connect.s: src/lcbio/connect.cc.s

.PHONY : src/lcbio/connect.s

# target to generate assembly for a file
src/lcbio/connect.cc.s:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/src/lcbio/connect.cc.s
.PHONY : src/lcbio/connect.cc.s

src/lcbio/ctx.o: src/lcbio/ctx.c.o

.PHONY : src/lcbio/ctx.o

# target to build an object file
src/lcbio/ctx.c.o:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/ctx.c.o
.PHONY : src/lcbio/ctx.c.o

src/lcbio/ctx.i: src/lcbio/ctx.c.i

.PHONY : src/lcbio/ctx.i

# target to preprocess a source file
src/lcbio/ctx.c.i:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/ctx.c.i
.PHONY : src/lcbio/ctx.c.i

src/lcbio/ctx.s: src/lcbio/ctx.c.s

.PHONY : src/lcbio/ctx.s

# target to generate assembly for a file
src/lcbio/ctx.c.s:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/ctx.c.s
.PHONY : src/lcbio/ctx.c.s

src/lcbio/iotable.o: src/lcbio/iotable.c.o

.PHONY : src/lcbio/iotable.o

# target to build an object file
src/lcbio/iotable.c.o:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/iotable.c.o
.PHONY : src/lcbio/iotable.c.o

src/lcbio/iotable.i: src/lcbio/iotable.c.i

.PHONY : src/lcbio/iotable.i

# target to preprocess a source file
src/lcbio/iotable.c.i:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/iotable.c.i
.PHONY : src/lcbio/iotable.c.i

src/lcbio/iotable.s: src/lcbio/iotable.c.s

.PHONY : src/lcbio/iotable.s

# target to generate assembly for a file
src/lcbio/iotable.c.s:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/iotable.c.s
.PHONY : src/lcbio/iotable.c.s

src/lcbio/ioutils.o: src/lcbio/ioutils.cc.o

.PHONY : src/lcbio/ioutils.o

# target to build an object file
src/lcbio/ioutils.cc.o:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/src/lcbio/ioutils.cc.o
.PHONY : src/lcbio/ioutils.cc.o

src/lcbio/ioutils.i: src/lcbio/ioutils.cc.i

.PHONY : src/lcbio/ioutils.i

# target to preprocess a source file
src/lcbio/ioutils.cc.i:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/src/lcbio/ioutils.cc.i
.PHONY : src/lcbio/ioutils.cc.i

src/lcbio/ioutils.s: src/lcbio/ioutils.cc.s

.PHONY : src/lcbio/ioutils.s

# target to generate assembly for a file
src/lcbio/ioutils.cc.s:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/src/lcbio/ioutils.cc.s
.PHONY : src/lcbio/ioutils.cc.s

src/lcbio/manager.o: src/lcbio/manager.cc.o

.PHONY : src/lcbio/manager.o

# target to build an object file
src/lcbio/manager.cc.o:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/src/lcbio/manager.cc.o
.PHONY : src/lcbio/manager.cc.o

src/lcbio/manager.i: src/lcbio/manager.cc.i

.PHONY : src/lcbio/manager.i

# target to preprocess a source file
src/lcbio/manager.cc.i:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/src/lcbio/manager.cc.i
.PHONY : src/lcbio/manager.cc.i

src/lcbio/manager.s: src/lcbio/manager.cc.s

.PHONY : src/lcbio/manager.s

# target to generate assembly for a file
src/lcbio/manager.cc.s:
	$(MAKE) -f CMakeFiles/lcbio-cxx.dir/build.make CMakeFiles/lcbio-cxx.dir/src/lcbio/manager.cc.s
.PHONY : src/lcbio/manager.cc.s

src/lcbio/protoctx.o: src/lcbio/protoctx.c.o

.PHONY : src/lcbio/protoctx.o

# target to build an object file
src/lcbio/protoctx.c.o:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/protoctx.c.o
.PHONY : src/lcbio/protoctx.c.o

src/lcbio/protoctx.i: src/lcbio/protoctx.c.i

.PHONY : src/lcbio/protoctx.i

# target to preprocess a source file
src/lcbio/protoctx.c.i:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/protoctx.c.i
.PHONY : src/lcbio/protoctx.c.i

src/lcbio/protoctx.s: src/lcbio/protoctx.c.s

.PHONY : src/lcbio/protoctx.s

# target to generate assembly for a file
src/lcbio/protoctx.c.s:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/protoctx.c.s
.PHONY : src/lcbio/protoctx.c.s

src/lcbio/timer.o: src/lcbio/timer.c.o

.PHONY : src/lcbio/timer.o

# target to build an object file
src/lcbio/timer.c.o:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/timer.c.o
.PHONY : src/lcbio/timer.c.o

src/lcbio/timer.i: src/lcbio/timer.c.i

.PHONY : src/lcbio/timer.i

# target to preprocess a source file
src/lcbio/timer.c.i:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/timer.c.i
.PHONY : src/lcbio/timer.c.i

src/lcbio/timer.s: src/lcbio/timer.c.s

.PHONY : src/lcbio/timer.s

# target to generate assembly for a file
src/lcbio/timer.c.s:
	$(MAKE) -f CMakeFiles/lcbio.dir/build.make CMakeFiles/lcbio.dir/src/lcbio/timer.c.s
.PHONY : src/lcbio/timer.c.s

src/legacy.o: src/legacy.c.o

.PHONY : src/legacy.o

# target to build an object file
src/legacy.c.o:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/legacy.c.o
.PHONY : src/legacy.c.o

src/legacy.i: src/legacy.c.i

.PHONY : src/legacy.i

# target to preprocess a source file
src/legacy.c.i:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/legacy.c.i
.PHONY : src/legacy.c.i

src/legacy.s: src/legacy.c.s

.PHONY : src/legacy.s

# target to generate assembly for a file
src/legacy.c.s:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/legacy.c.s
.PHONY : src/legacy.c.s

src/list.o: src/list.c.o

.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/list.c.s
.PHONY : src/list.c.s

src/logging.o: src/logging.c.o

.PHONY : src/logging.o

# target to build an object file
src/logging.c.o:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/logging.c.o
.PHONY : src/logging.c.o

src/logging.i: src/logging.c.i

.PHONY : src/logging.i

# target to preprocess a source file
src/logging.c.i:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/logging.c.i
.PHONY : src/logging.c.i

src/logging.s: src/logging.c.s

.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.c.s:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/logging.c.s
.PHONY : src/logging.c.s

src/mc/compress.o: src/mc/compress.cc.o

.PHONY : src/mc/compress.o

# target to build an object file
src/mc/compress.cc.o:
	$(MAKE) -f CMakeFiles/mcreq-cxx.dir/build.make CMakeFiles/mcreq-cxx.dir/src/mc/compress.cc.o
.PHONY : src/mc/compress.cc.o

src/mc/compress.i: src/mc/compress.cc.i

.PHONY : src/mc/compress.i

# target to preprocess a source file
src/mc/compress.cc.i:
	$(MAKE) -f CMakeFiles/mcreq-cxx.dir/build.make CMakeFiles/mcreq-cxx.dir/src/mc/compress.cc.i
.PHONY : src/mc/compress.cc.i

src/mc/compress.s: src/mc/compress.cc.s

.PHONY : src/mc/compress.s

# target to generate assembly for a file
src/mc/compress.cc.s:
	$(MAKE) -f CMakeFiles/mcreq-cxx.dir/build.make CMakeFiles/mcreq-cxx.dir/src/mc/compress.cc.s
.PHONY : src/mc/compress.cc.s

src/mc/forward.o: src/mc/forward.c.o

.PHONY : src/mc/forward.o

# target to build an object file
src/mc/forward.c.o:
	$(MAKE) -f CMakeFiles/mcreq.dir/build.make CMakeFiles/mcreq.dir/src/mc/forward.c.o
.PHONY : src/mc/forward.c.o

src/mc/forward.i: src/mc/forward.c.i

.PHONY : src/mc/forward.i

# target to preprocess a source file
src/mc/forward.c.i:
	$(MAKE) -f CMakeFiles/mcreq.dir/build.make CMakeFiles/mcreq.dir/src/mc/forward.c.i
.PHONY : src/mc/forward.c.i

src/mc/forward.s: src/mc/forward.c.s

.PHONY : src/mc/forward.s

# target to generate assembly for a file
src/mc/forward.c.s:
	$(MAKE) -f CMakeFiles/mcreq.dir/build.make CMakeFiles/mcreq.dir/src/mc/forward.c.s
.PHONY : src/mc/forward.c.s

src/mc/mcreq.o: src/mc/mcreq.c.o

.PHONY : src/mc/mcreq.o

# target to build an object file
src/mc/mcreq.c.o:
	$(MAKE) -f CMakeFiles/mcreq.dir/build.make CMakeFiles/mcreq.dir/src/mc/mcreq.c.o
.PHONY : src/mc/mcreq.c.o

src/mc/mcreq.i: src/mc/mcreq.c.i

.PHONY : src/mc/mcreq.i

# target to preprocess a source file
src/mc/mcreq.c.i:
	$(MAKE) -f CMakeFiles/mcreq.dir/build.make CMakeFiles/mcreq.dir/src/mc/mcreq.c.i
.PHONY : src/mc/mcreq.c.i

src/mc/mcreq.s: src/mc/mcreq.c.s

.PHONY : src/mc/mcreq.s

# target to generate assembly for a file
src/mc/mcreq.c.s:
	$(MAKE) -f CMakeFiles/mcreq.dir/build.make CMakeFiles/mcreq.dir/src/mc/mcreq.c.s
.PHONY : src/mc/mcreq.c.s

src/mcserver/mcserver.o: src/mcserver/mcserver.cc.o

.PHONY : src/mcserver/mcserver.o

# target to build an object file
src/mcserver/mcserver.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/mcserver/mcserver.cc.o
.PHONY : src/mcserver/mcserver.cc.o

src/mcserver/mcserver.i: src/mcserver/mcserver.cc.i

.PHONY : src/mcserver/mcserver.i

# target to preprocess a source file
src/mcserver/mcserver.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/mcserver/mcserver.cc.i
.PHONY : src/mcserver/mcserver.cc.i

src/mcserver/mcserver.s: src/mcserver/mcserver.cc.s

.PHONY : src/mcserver/mcserver.s

# target to generate assembly for a file
src/mcserver/mcserver.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/mcserver/mcserver.cc.s
.PHONY : src/mcserver/mcserver.cc.s

src/mcserver/negotiate.o: src/mcserver/negotiate.cc.o

.PHONY : src/mcserver/negotiate.o

# target to build an object file
src/mcserver/negotiate.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/mcserver/negotiate.cc.o
.PHONY : src/mcserver/negotiate.cc.o

src/mcserver/negotiate.i: src/mcserver/negotiate.cc.i

.PHONY : src/mcserver/negotiate.i

# target to preprocess a source file
src/mcserver/negotiate.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/mcserver/negotiate.cc.i
.PHONY : src/mcserver/negotiate.cc.i

src/mcserver/negotiate.s: src/mcserver/negotiate.cc.s

.PHONY : src/mcserver/negotiate.s

# target to generate assembly for a file
src/mcserver/negotiate.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/mcserver/negotiate.cc.s
.PHONY : src/mcserver/negotiate.cc.s

src/metrics.o: src/metrics.cc.o

.PHONY : src/metrics.o

# target to build an object file
src/metrics.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/metrics.cc.o
.PHONY : src/metrics.cc.o

src/metrics.i: src/metrics.cc.i

.PHONY : src/metrics.i

# target to preprocess a source file
src/metrics.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/metrics.cc.i
.PHONY : src/metrics.cc.i

src/metrics.s: src/metrics.cc.s

.PHONY : src/metrics.s

# target to generate assembly for a file
src/metrics.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/metrics.cc.s
.PHONY : src/metrics.cc.s

src/n1ql/ixmgmt.o: src/n1ql/ixmgmt.cc.o

.PHONY : src/n1ql/ixmgmt.o

# target to build an object file
src/n1ql/ixmgmt.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/n1ql/ixmgmt.cc.o
.PHONY : src/n1ql/ixmgmt.cc.o

src/n1ql/ixmgmt.i: src/n1ql/ixmgmt.cc.i

.PHONY : src/n1ql/ixmgmt.i

# target to preprocess a source file
src/n1ql/ixmgmt.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/n1ql/ixmgmt.cc.i
.PHONY : src/n1ql/ixmgmt.cc.i

src/n1ql/ixmgmt.s: src/n1ql/ixmgmt.cc.s

.PHONY : src/n1ql/ixmgmt.s

# target to generate assembly for a file
src/n1ql/ixmgmt.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/n1ql/ixmgmt.cc.s
.PHONY : src/n1ql/ixmgmt.cc.s

src/n1ql/n1ql.o: src/n1ql/n1ql.cc.o

.PHONY : src/n1ql/n1ql.o

# target to build an object file
src/n1ql/n1ql.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/n1ql/n1ql.cc.o
.PHONY : src/n1ql/n1ql.cc.o

src/n1ql/n1ql.i: src/n1ql/n1ql.cc.i

.PHONY : src/n1ql/n1ql.i

# target to preprocess a source file
src/n1ql/n1ql.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/n1ql/n1ql.cc.i
.PHONY : src/n1ql/n1ql.cc.i

src/n1ql/n1ql.s: src/n1ql/n1ql.cc.s

.PHONY : src/n1ql/n1ql.s

# target to generate assembly for a file
src/n1ql/n1ql.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/n1ql/n1ql.cc.s
.PHONY : src/n1ql/n1ql.cc.s

src/n1ql/params.o: src/n1ql/params.cc.o

.PHONY : src/n1ql/params.o

# target to build an object file
src/n1ql/params.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/n1ql/params.cc.o
.PHONY : src/n1ql/params.cc.o

src/n1ql/params.i: src/n1ql/params.cc.i

.PHONY : src/n1ql/params.i

# target to preprocess a source file
src/n1ql/params.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/n1ql/params.cc.i
.PHONY : src/n1ql/params.cc.i

src/n1ql/params.s: src/n1ql/params.cc.s

.PHONY : src/n1ql/params.s

# target to generate assembly for a file
src/n1ql/params.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/n1ql/params.cc.s
.PHONY : src/n1ql/params.cc.s

src/netbuf/netbuf.o: src/netbuf/netbuf.c.o

.PHONY : src/netbuf/netbuf.o

# target to build an object file
src/netbuf/netbuf.c.o:
	$(MAKE) -f CMakeFiles/netbuf.dir/build.make CMakeFiles/netbuf.dir/src/netbuf/netbuf.c.o
	$(MAKE) -f CMakeFiles/netbuf-malloc.dir/build.make CMakeFiles/netbuf-malloc.dir/src/netbuf/netbuf.c.o
.PHONY : src/netbuf/netbuf.c.o

src/netbuf/netbuf.i: src/netbuf/netbuf.c.i

.PHONY : src/netbuf/netbuf.i

# target to preprocess a source file
src/netbuf/netbuf.c.i:
	$(MAKE) -f CMakeFiles/netbuf.dir/build.make CMakeFiles/netbuf.dir/src/netbuf/netbuf.c.i
	$(MAKE) -f CMakeFiles/netbuf-malloc.dir/build.make CMakeFiles/netbuf-malloc.dir/src/netbuf/netbuf.c.i
.PHONY : src/netbuf/netbuf.c.i

src/netbuf/netbuf.s: src/netbuf/netbuf.c.s

.PHONY : src/netbuf/netbuf.s

# target to generate assembly for a file
src/netbuf/netbuf.c.s:
	$(MAKE) -f CMakeFiles/netbuf.dir/build.make CMakeFiles/netbuf.dir/src/netbuf/netbuf.c.s
	$(MAKE) -f CMakeFiles/netbuf-malloc.dir/build.make CMakeFiles/netbuf-malloc.dir/src/netbuf/netbuf.c.s
.PHONY : src/netbuf/netbuf.c.s

src/newconfig.o: src/newconfig.cc.o

.PHONY : src/newconfig.o

# target to build an object file
src/newconfig.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/newconfig.cc.o
.PHONY : src/newconfig.cc.o

src/newconfig.i: src/newconfig.cc.i

.PHONY : src/newconfig.i

# target to preprocess a source file
src/newconfig.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/newconfig.cc.i
.PHONY : src/newconfig.cc.i

src/newconfig.s: src/newconfig.cc.s

.PHONY : src/newconfig.s

# target to generate assembly for a file
src/newconfig.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/newconfig.cc.s
.PHONY : src/newconfig.cc.s

src/nodeinfo.o: src/nodeinfo.cc.o

.PHONY : src/nodeinfo.o

# target to build an object file
src/nodeinfo.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/nodeinfo.cc.o
.PHONY : src/nodeinfo.cc.o

src/nodeinfo.i: src/nodeinfo.cc.i

.PHONY : src/nodeinfo.i

# target to preprocess a source file
src/nodeinfo.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/nodeinfo.cc.i
.PHONY : src/nodeinfo.cc.i

src/nodeinfo.s: src/nodeinfo.cc.s

.PHONY : src/nodeinfo.s

# target to generate assembly for a file
src/nodeinfo.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/nodeinfo.cc.s
.PHONY : src/nodeinfo.cc.s

src/operations/cbflush.o: src/operations/cbflush.cc.o

.PHONY : src/operations/cbflush.o

# target to build an object file
src/operations/cbflush.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/cbflush.cc.o
.PHONY : src/operations/cbflush.cc.o

src/operations/cbflush.i: src/operations/cbflush.cc.i

.PHONY : src/operations/cbflush.i

# target to preprocess a source file
src/operations/cbflush.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/cbflush.cc.i
.PHONY : src/operations/cbflush.cc.i

src/operations/cbflush.s: src/operations/cbflush.cc.s

.PHONY : src/operations/cbflush.s

# target to generate assembly for a file
src/operations/cbflush.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/cbflush.cc.s
.PHONY : src/operations/cbflush.cc.s

src/operations/counter.o: src/operations/counter.cc.o

.PHONY : src/operations/counter.o

# target to build an object file
src/operations/counter.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/counter.cc.o
.PHONY : src/operations/counter.cc.o

src/operations/counter.i: src/operations/counter.cc.i

.PHONY : src/operations/counter.i

# target to preprocess a source file
src/operations/counter.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/counter.cc.i
.PHONY : src/operations/counter.cc.i

src/operations/counter.s: src/operations/counter.cc.s

.PHONY : src/operations/counter.s

# target to generate assembly for a file
src/operations/counter.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/counter.cc.s
.PHONY : src/operations/counter.cc.s

src/operations/durability-cas.o: src/operations/durability-cas.cc.o

.PHONY : src/operations/durability-cas.o

# target to build an object file
src/operations/durability-cas.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/durability-cas.cc.o
.PHONY : src/operations/durability-cas.cc.o

src/operations/durability-cas.i: src/operations/durability-cas.cc.i

.PHONY : src/operations/durability-cas.i

# target to preprocess a source file
src/operations/durability-cas.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/durability-cas.cc.i
.PHONY : src/operations/durability-cas.cc.i

src/operations/durability-cas.s: src/operations/durability-cas.cc.s

.PHONY : src/operations/durability-cas.s

# target to generate assembly for a file
src/operations/durability-cas.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/durability-cas.cc.s
.PHONY : src/operations/durability-cas.cc.s

src/operations/durability-seqno.o: src/operations/durability-seqno.cc.o

.PHONY : src/operations/durability-seqno.o

# target to build an object file
src/operations/durability-seqno.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/durability-seqno.cc.o
.PHONY : src/operations/durability-seqno.cc.o

src/operations/durability-seqno.i: src/operations/durability-seqno.cc.i

.PHONY : src/operations/durability-seqno.i

# target to preprocess a source file
src/operations/durability-seqno.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/durability-seqno.cc.i
.PHONY : src/operations/durability-seqno.cc.i

src/operations/durability-seqno.s: src/operations/durability-seqno.cc.s

.PHONY : src/operations/durability-seqno.s

# target to generate assembly for a file
src/operations/durability-seqno.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/durability-seqno.cc.s
.PHONY : src/operations/durability-seqno.cc.s

src/operations/durability.o: src/operations/durability.cc.o

.PHONY : src/operations/durability.o

# target to build an object file
src/operations/durability.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/durability.cc.o
.PHONY : src/operations/durability.cc.o

src/operations/durability.i: src/operations/durability.cc.i

.PHONY : src/operations/durability.i

# target to preprocess a source file
src/operations/durability.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/durability.cc.i
.PHONY : src/operations/durability.cc.i

src/operations/durability.s: src/operations/durability.cc.s

.PHONY : src/operations/durability.s

# target to generate assembly for a file
src/operations/durability.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/durability.cc.s
.PHONY : src/operations/durability.cc.s

src/operations/get.o: src/operations/get.cc.o

.PHONY : src/operations/get.o

# target to build an object file
src/operations/get.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/get.cc.o
.PHONY : src/operations/get.cc.o

src/operations/get.i: src/operations/get.cc.i

.PHONY : src/operations/get.i

# target to preprocess a source file
src/operations/get.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/get.cc.i
.PHONY : src/operations/get.cc.i

src/operations/get.s: src/operations/get.cc.s

.PHONY : src/operations/get.s

# target to generate assembly for a file
src/operations/get.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/get.cc.s
.PHONY : src/operations/get.cc.s

src/operations/observe-seqno.o: src/operations/observe-seqno.cc.o

.PHONY : src/operations/observe-seqno.o

# target to build an object file
src/operations/observe-seqno.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/observe-seqno.cc.o
.PHONY : src/operations/observe-seqno.cc.o

src/operations/observe-seqno.i: src/operations/observe-seqno.cc.i

.PHONY : src/operations/observe-seqno.i

# target to preprocess a source file
src/operations/observe-seqno.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/observe-seqno.cc.i
.PHONY : src/operations/observe-seqno.cc.i

src/operations/observe-seqno.s: src/operations/observe-seqno.cc.s

.PHONY : src/operations/observe-seqno.s

# target to generate assembly for a file
src/operations/observe-seqno.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/observe-seqno.cc.s
.PHONY : src/operations/observe-seqno.cc.s

src/operations/observe.o: src/operations/observe.cc.o

.PHONY : src/operations/observe.o

# target to build an object file
src/operations/observe.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/observe.cc.o
.PHONY : src/operations/observe.cc.o

src/operations/observe.i: src/operations/observe.cc.i

.PHONY : src/operations/observe.i

# target to preprocess a source file
src/operations/observe.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/observe.cc.i
.PHONY : src/operations/observe.cc.i

src/operations/observe.s: src/operations/observe.cc.s

.PHONY : src/operations/observe.s

# target to generate assembly for a file
src/operations/observe.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/observe.cc.s
.PHONY : src/operations/observe.cc.s

src/operations/ping.o: src/operations/ping.cc.o

.PHONY : src/operations/ping.o

# target to build an object file
src/operations/ping.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/ping.cc.o
.PHONY : src/operations/ping.cc.o

src/operations/ping.i: src/operations/ping.cc.i

.PHONY : src/operations/ping.i

# target to preprocess a source file
src/operations/ping.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/ping.cc.i
.PHONY : src/operations/ping.cc.i

src/operations/ping.s: src/operations/ping.cc.s

.PHONY : src/operations/ping.s

# target to generate assembly for a file
src/operations/ping.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/ping.cc.s
.PHONY : src/operations/ping.cc.s

src/operations/pktfwd.o: src/operations/pktfwd.cc.o

.PHONY : src/operations/pktfwd.o

# target to build an object file
src/operations/pktfwd.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/pktfwd.cc.o
.PHONY : src/operations/pktfwd.cc.o

src/operations/pktfwd.i: src/operations/pktfwd.cc.i

.PHONY : src/operations/pktfwd.i

# target to preprocess a source file
src/operations/pktfwd.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/pktfwd.cc.i
.PHONY : src/operations/pktfwd.cc.i

src/operations/pktfwd.s: src/operations/pktfwd.cc.s

.PHONY : src/operations/pktfwd.s

# target to generate assembly for a file
src/operations/pktfwd.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/pktfwd.cc.s
.PHONY : src/operations/pktfwd.cc.s

src/operations/remove.o: src/operations/remove.cc.o

.PHONY : src/operations/remove.o

# target to build an object file
src/operations/remove.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/remove.cc.o
.PHONY : src/operations/remove.cc.o

src/operations/remove.i: src/operations/remove.cc.i

.PHONY : src/operations/remove.i

# target to preprocess a source file
src/operations/remove.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/remove.cc.i
.PHONY : src/operations/remove.cc.i

src/operations/remove.s: src/operations/remove.cc.s

.PHONY : src/operations/remove.s

# target to generate assembly for a file
src/operations/remove.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/remove.cc.s
.PHONY : src/operations/remove.cc.s

src/operations/stats.o: src/operations/stats.cc.o

.PHONY : src/operations/stats.o

# target to build an object file
src/operations/stats.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/stats.cc.o
.PHONY : src/operations/stats.cc.o

src/operations/stats.i: src/operations/stats.cc.i

.PHONY : src/operations/stats.i

# target to preprocess a source file
src/operations/stats.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/stats.cc.i
.PHONY : src/operations/stats.cc.i

src/operations/stats.s: src/operations/stats.cc.s

.PHONY : src/operations/stats.s

# target to generate assembly for a file
src/operations/stats.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/stats.cc.s
.PHONY : src/operations/stats.cc.s

src/operations/store.o: src/operations/store.cc.o

.PHONY : src/operations/store.o

# target to build an object file
src/operations/store.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/store.cc.o
.PHONY : src/operations/store.cc.o

src/operations/store.i: src/operations/store.cc.i

.PHONY : src/operations/store.i

# target to preprocess a source file
src/operations/store.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/store.cc.i
.PHONY : src/operations/store.cc.i

src/operations/store.s: src/operations/store.cc.s

.PHONY : src/operations/store.s

# target to generate assembly for a file
src/operations/store.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/store.cc.s
.PHONY : src/operations/store.cc.s

src/operations/subdoc.o: src/operations/subdoc.cc.o

.PHONY : src/operations/subdoc.o

# target to build an object file
src/operations/subdoc.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/subdoc.cc.o
.PHONY : src/operations/subdoc.cc.o

src/operations/subdoc.i: src/operations/subdoc.cc.i

.PHONY : src/operations/subdoc.i

# target to preprocess a source file
src/operations/subdoc.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/subdoc.cc.i
.PHONY : src/operations/subdoc.cc.i

src/operations/subdoc.s: src/operations/subdoc.cc.s

.PHONY : src/operations/subdoc.s

# target to generate assembly for a file
src/operations/subdoc.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/subdoc.cc.s
.PHONY : src/operations/subdoc.cc.s

src/operations/touch.o: src/operations/touch.cc.o

.PHONY : src/operations/touch.o

# target to build an object file
src/operations/touch.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/touch.cc.o
.PHONY : src/operations/touch.cc.o

src/operations/touch.i: src/operations/touch.cc.i

.PHONY : src/operations/touch.i

# target to preprocess a source file
src/operations/touch.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/touch.cc.i
.PHONY : src/operations/touch.cc.i

src/operations/touch.s: src/operations/touch.cc.s

.PHONY : src/operations/touch.s

# target to generate assembly for a file
src/operations/touch.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/operations/touch.cc.s
.PHONY : src/operations/touch.cc.s

src/rdb/bigalloc.o: src/rdb/bigalloc.c.o

.PHONY : src/rdb/bigalloc.o

# target to build an object file
src/rdb/bigalloc.c.o:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/bigalloc.c.o
.PHONY : src/rdb/bigalloc.c.o

src/rdb/bigalloc.i: src/rdb/bigalloc.c.i

.PHONY : src/rdb/bigalloc.i

# target to preprocess a source file
src/rdb/bigalloc.c.i:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/bigalloc.c.i
.PHONY : src/rdb/bigalloc.c.i

src/rdb/bigalloc.s: src/rdb/bigalloc.c.s

.PHONY : src/rdb/bigalloc.s

# target to generate assembly for a file
src/rdb/bigalloc.c.s:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/bigalloc.c.s
.PHONY : src/rdb/bigalloc.c.s

src/rdb/chunkalloc.o: src/rdb/chunkalloc.c.o

.PHONY : src/rdb/chunkalloc.o

# target to build an object file
src/rdb/chunkalloc.c.o:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/chunkalloc.c.o
.PHONY : src/rdb/chunkalloc.c.o

src/rdb/chunkalloc.i: src/rdb/chunkalloc.c.i

.PHONY : src/rdb/chunkalloc.i

# target to preprocess a source file
src/rdb/chunkalloc.c.i:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/chunkalloc.c.i
.PHONY : src/rdb/chunkalloc.c.i

src/rdb/chunkalloc.s: src/rdb/chunkalloc.c.s

.PHONY : src/rdb/chunkalloc.s

# target to generate assembly for a file
src/rdb/chunkalloc.c.s:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/chunkalloc.c.s
.PHONY : src/rdb/chunkalloc.c.s

src/rdb/libcalloc.o: src/rdb/libcalloc.c.o

.PHONY : src/rdb/libcalloc.o

# target to build an object file
src/rdb/libcalloc.c.o:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/libcalloc.c.o
.PHONY : src/rdb/libcalloc.c.o

src/rdb/libcalloc.i: src/rdb/libcalloc.c.i

.PHONY : src/rdb/libcalloc.i

# target to preprocess a source file
src/rdb/libcalloc.c.i:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/libcalloc.c.i
.PHONY : src/rdb/libcalloc.c.i

src/rdb/libcalloc.s: src/rdb/libcalloc.c.s

.PHONY : src/rdb/libcalloc.s

# target to generate assembly for a file
src/rdb/libcalloc.c.s:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/libcalloc.c.s
.PHONY : src/rdb/libcalloc.c.s

src/rdb/rope.o: src/rdb/rope.c.o

.PHONY : src/rdb/rope.o

# target to build an object file
src/rdb/rope.c.o:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/rope.c.o
.PHONY : src/rdb/rope.c.o

src/rdb/rope.i: src/rdb/rope.c.i

.PHONY : src/rdb/rope.i

# target to preprocess a source file
src/rdb/rope.c.i:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/rope.c.i
.PHONY : src/rdb/rope.c.i

src/rdb/rope.s: src/rdb/rope.c.s

.PHONY : src/rdb/rope.s

# target to generate assembly for a file
src/rdb/rope.c.s:
	$(MAKE) -f CMakeFiles/rdb.dir/build.make CMakeFiles/rdb.dir/src/rdb/rope.c.s
.PHONY : src/rdb/rope.c.s

src/retrychk.o: src/retrychk.cc.o

.PHONY : src/retrychk.o

# target to build an object file
src/retrychk.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/retrychk.cc.o
.PHONY : src/retrychk.cc.o

src/retrychk.i: src/retrychk.cc.i

.PHONY : src/retrychk.i

# target to preprocess a source file
src/retrychk.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/retrychk.cc.i
.PHONY : src/retrychk.cc.i

src/retrychk.s: src/retrychk.cc.s

.PHONY : src/retrychk.s

# target to generate assembly for a file
src/retrychk.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/retrychk.cc.s
.PHONY : src/retrychk.cc.s

src/retryq.o: src/retryq.cc.o

.PHONY : src/retryq.o

# target to build an object file
src/retryq.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/retryq.cc.o
.PHONY : src/retryq.cc.o

src/retryq.i: src/retryq.cc.i

.PHONY : src/retryq.i

# target to preprocess a source file
src/retryq.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/retryq.cc.i
.PHONY : src/retryq.cc.i

src/retryq.s: src/retryq.cc.s

.PHONY : src/retryq.s

# target to generate assembly for a file
src/retryq.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/retryq.cc.s
.PHONY : src/retryq.cc.s

src/ringbuffer.o: src/ringbuffer.c.o

.PHONY : src/ringbuffer.o

# target to build an object file
src/ringbuffer.c.o:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/ringbuffer.c.o
.PHONY : src/ringbuffer.c.o

src/ringbuffer.i: src/ringbuffer.c.i

.PHONY : src/ringbuffer.i

# target to preprocess a source file
src/ringbuffer.c.i:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/ringbuffer.c.i
.PHONY : src/ringbuffer.c.i

src/ringbuffer.s: src/ringbuffer.c.s

.PHONY : src/ringbuffer.s

# target to generate assembly for a file
src/ringbuffer.c.s:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/ringbuffer.c.s
.PHONY : src/ringbuffer.c.s

src/rnd.o: src/rnd.cc.o

.PHONY : src/rnd.o

# target to build an object file
src/rnd.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/rnd.cc.o
.PHONY : src/rnd.cc.o

src/rnd.i: src/rnd.cc.i

.PHONY : src/rnd.i

# target to preprocess a source file
src/rnd.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/rnd.cc.i
.PHONY : src/rnd.cc.i

src/rnd.s: src/rnd.cc.s

.PHONY : src/rnd.s

# target to generate assembly for a file
src/rnd.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/rnd.cc.s
.PHONY : src/rnd.cc.s

src/settings.o: src/settings.c.o

.PHONY : src/settings.o

# target to build an object file
src/settings.c.o:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/settings.c.o
.PHONY : src/settings.c.o

src/settings.i: src/settings.c.i

.PHONY : src/settings.i

# target to preprocess a source file
src/settings.c.i:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/settings.c.i
.PHONY : src/settings.c.i

src/settings.s: src/settings.c.s

.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.c.s:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/settings.c.s
.PHONY : src/settings.c.s

src/strcodecs/base64.o: src/strcodecs/base64.c.o

.PHONY : src/strcodecs/base64.o

# target to build an object file
src/strcodecs/base64.c.o:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/strcodecs/base64.c.o
.PHONY : src/strcodecs/base64.c.o

src/strcodecs/base64.i: src/strcodecs/base64.c.i

.PHONY : src/strcodecs/base64.i

# target to preprocess a source file
src/strcodecs/base64.c.i:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/strcodecs/base64.c.i
.PHONY : src/strcodecs/base64.c.i

src/strcodecs/base64.s: src/strcodecs/base64.c.s

.PHONY : src/strcodecs/base64.s

# target to generate assembly for a file
src/strcodecs/base64.c.s:
	$(MAKE) -f CMakeFiles/couchbase_utils.dir/build.make CMakeFiles/couchbase_utils.dir/src/strcodecs/base64.c.s
.PHONY : src/strcodecs/base64.c.s

src/timings.o: src/timings.c.o

.PHONY : src/timings.o

# target to build an object file
src/timings.c.o:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/timings.c.o
.PHONY : src/timings.c.o

src/timings.i: src/timings.c.i

.PHONY : src/timings.i

# target to preprocess a source file
src/timings.c.i:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/timings.c.i
.PHONY : src/timings.c.i

src/timings.s: src/timings.c.s

.PHONY : src/timings.s

# target to generate assembly for a file
src/timings.c.s:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/timings.c.s
.PHONY : src/timings.c.s

src/tracing/span.o: src/tracing/span.cc.o

.PHONY : src/tracing/span.o

# target to build an object file
src/tracing/span.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/tracing/span.cc.o
.PHONY : src/tracing/span.cc.o

src/tracing/span.i: src/tracing/span.cc.i

.PHONY : src/tracing/span.i

# target to preprocess a source file
src/tracing/span.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/tracing/span.cc.i
.PHONY : src/tracing/span.cc.i

src/tracing/span.s: src/tracing/span.cc.s

.PHONY : src/tracing/span.s

# target to generate assembly for a file
src/tracing/span.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/tracing/span.cc.s
.PHONY : src/tracing/span.cc.s

src/tracing/threshold_logging_tracer.o: src/tracing/threshold_logging_tracer.cc.o

.PHONY : src/tracing/threshold_logging_tracer.o

# target to build an object file
src/tracing/threshold_logging_tracer.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/tracing/threshold_logging_tracer.cc.o
.PHONY : src/tracing/threshold_logging_tracer.cc.o

src/tracing/threshold_logging_tracer.i: src/tracing/threshold_logging_tracer.cc.i

.PHONY : src/tracing/threshold_logging_tracer.i

# target to preprocess a source file
src/tracing/threshold_logging_tracer.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/tracing/threshold_logging_tracer.cc.i
.PHONY : src/tracing/threshold_logging_tracer.cc.i

src/tracing/threshold_logging_tracer.s: src/tracing/threshold_logging_tracer.cc.s

.PHONY : src/tracing/threshold_logging_tracer.s

# target to generate assembly for a file
src/tracing/threshold_logging_tracer.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/tracing/threshold_logging_tracer.cc.s
.PHONY : src/tracing/threshold_logging_tracer.cc.s

src/tracing/tracer.o: src/tracing/tracer.cc.o

.PHONY : src/tracing/tracer.o

# target to build an object file
src/tracing/tracer.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/tracing/tracer.cc.o
.PHONY : src/tracing/tracer.cc.o

src/tracing/tracer.i: src/tracing/tracer.cc.i

.PHONY : src/tracing/tracer.i

# target to preprocess a source file
src/tracing/tracer.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/tracing/tracer.cc.i
.PHONY : src/tracing/tracer.cc.i

src/tracing/tracer.s: src/tracing/tracer.cc.s

.PHONY : src/tracing/tracer.s

# target to generate assembly for a file
src/tracing/tracer.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/tracing/tracer.cc.s
.PHONY : src/tracing/tracer.cc.s

src/utilities.o: src/utilities.c.o

.PHONY : src/utilities.o

# target to build an object file
src/utilities.c.o:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/utilities.c.o
.PHONY : src/utilities.c.o

src/utilities.i: src/utilities.c.i

.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.c.i:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/utilities.c.i
.PHONY : src/utilities.c.i

src/utilities.s: src/utilities.c.s

.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.c.s:
	$(MAKE) -f CMakeFiles/lcbcore.dir/build.make CMakeFiles/lcbcore.dir/src/utilities.c.s
.PHONY : src/utilities.c.s

src/views/docreq.o: src/views/docreq.cc.o

.PHONY : src/views/docreq.o

# target to build an object file
src/views/docreq.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/views/docreq.cc.o
.PHONY : src/views/docreq.cc.o

src/views/docreq.i: src/views/docreq.cc.i

.PHONY : src/views/docreq.i

# target to preprocess a source file
src/views/docreq.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/views/docreq.cc.i
.PHONY : src/views/docreq.cc.i

src/views/docreq.s: src/views/docreq.cc.s

.PHONY : src/views/docreq.s

# target to generate assembly for a file
src/views/docreq.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/views/docreq.cc.s
.PHONY : src/views/docreq.cc.s

src/views/viewreq.o: src/views/viewreq.cc.o

.PHONY : src/views/viewreq.o

# target to build an object file
src/views/viewreq.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/views/viewreq.cc.o
.PHONY : src/views/viewreq.cc.o

src/views/viewreq.i: src/views/viewreq.cc.i

.PHONY : src/views/viewreq.i

# target to preprocess a source file
src/views/viewreq.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/views/viewreq.cc.i
.PHONY : src/views/viewreq.cc.i

src/views/viewreq.s: src/views/viewreq.cc.s

.PHONY : src/views/viewreq.s

# target to generate assembly for a file
src/views/viewreq.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/views/viewreq.cc.s
.PHONY : src/views/viewreq.cc.s

src/wait.o: src/wait.cc.o

.PHONY : src/wait.o

# target to build an object file
src/wait.cc.o:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/wait.cc.o
.PHONY : src/wait.cc.o

src/wait.i: src/wait.cc.i

.PHONY : src/wait.i

# target to preprocess a source file
src/wait.cc.i:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/wait.cc.i
.PHONY : src/wait.cc.i

src/wait.s: src/wait.cc.s

.PHONY : src/wait.s

# target to generate assembly for a file
src/wait.cc.s:
	$(MAKE) -f CMakeFiles/lcbcore-cxx.dir/build.make CMakeFiles/lcbcore-cxx.dir/src/wait.cc.s
.PHONY : src/wait.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package_source"
	@echo "... couchbaseS"
	@echo "... edit_cache"
	@echo "... mcreq"
	@echo "... package"
	@echo "... couchbase_utils"
	@echo "... lcbio-cxx"
	@echo "... uninstall"
	@echo "... install"
	@echo "... netbuf"
	@echo "... mcreq-cxx"
	@echo "... install/local"
	@echo "... test"
	@echo "... netbuf-malloc"
	@echo "... lcbcore"
	@echo "... lcbcore-cxx"
	@echo "... lcb_jsparse"
	@echo "... couchbase"
	@echo "... rdb"
	@echo "... dist"
	@echo "... file_manifest"
	@echo "... lcbio"
	@echo "... lcbht"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vbucket"
	@echo "... cbsasl"
	@echo "... cliopts"
	@echo "... lcbssl"
	@echo "... lcb_jsoncpp"
	@echo "... lcb_snappy"
	@echo "... alltests"
	@echo "... unit-tests"
	@echo "... mocksupport"
	@echo "... mc-tests"
	@echo "... nonio-tests"
	@echo "... check-all"
	@echo "... ioserver"
	@echo "... mc-malloc-tests"
	@echo "... netbuf-tests"
	@echo "... sock-tests"
	@echo "... rdb-tests"
	@echo "... vbucket-tests"
	@echo "... htparse-tests"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... cbc-n1qlback"
	@echo "... cbc-pillowfight"
	@echo "... linenoise"
	@echo "... cbc"
	@echo "... lcbtools"
	@echo "... cbc-subdoc"
	@echo "... couchbase_select"
	@echo "... contrib/genhash/genhash.o"
	@echo "... contrib/genhash/genhash.i"
	@echo "... contrib/genhash/genhash.s"
	@echo "... contrib/http_parser/http_parser.o"
	@echo "... contrib/http_parser/http_parser.i"
	@echo "... contrib/http_parser/http_parser.s"
	@echo "... src/auth.o"
	@echo "... src/auth.i"
	@echo "... src/auth.s"
	@echo "... src/bootstrap.o"
	@echo "... src/bootstrap.i"
	@echo "... src/bootstrap.s"
	@echo "... src/bucketconfig/bc_cccp.o"
	@echo "... src/bucketconfig/bc_cccp.i"
	@echo "... src/bucketconfig/bc_cccp.s"
	@echo "... src/bucketconfig/bc_file.o"
	@echo "... src/bucketconfig/bc_file.i"
	@echo "... src/bucketconfig/bc_file.s"
	@echo "... src/bucketconfig/bc_http.o"
	@echo "... src/bucketconfig/bc_http.i"
	@echo "... src/bucketconfig/bc_http.s"
	@echo "... src/bucketconfig/bc_static.o"
	@echo "... src/bucketconfig/bc_static.i"
	@echo "... src/bucketconfig/bc_static.s"
	@echo "... src/bucketconfig/confmon.o"
	@echo "... src/bucketconfig/confmon.i"
	@echo "... src/bucketconfig/confmon.s"
	@echo "... src/callbacks.o"
	@echo "... src/callbacks.i"
	@echo "... src/callbacks.s"
	@echo "... src/cbft.o"
	@echo "... src/cbft.i"
	@echo "... src/cbft.s"
	@echo "... src/cntl.o"
	@echo "... src/cntl.i"
	@echo "... src/cntl.s"
	@echo "... src/connspec.o"
	@echo "... src/connspec.i"
	@echo "... src/connspec.s"
	@echo "... src/crypto.o"
	@echo "... src/crypto.i"
	@echo "... src/crypto.s"
	@echo "... src/dns-srv.o"
	@echo "... src/dns-srv.i"
	@echo "... src/dns-srv.s"
	@echo "... src/dump.o"
	@echo "... src/dump.i"
	@echo "... src/dump.s"
	@echo "... src/errmap.o"
	@echo "... src/errmap.i"
	@echo "... src/errmap.s"
	@echo "... src/getconfig.o"
	@echo "... src/getconfig.i"
	@echo "... src/getconfig.s"
	@echo "... src/gethrtime.o"
	@echo "... src/gethrtime.i"
	@echo "... src/gethrtime.s"
	@echo "... src/handler.o"
	@echo "... src/handler.i"
	@echo "... src/handler.s"
	@echo "... src/hashtable.o"
	@echo "... src/hashtable.i"
	@echo "... src/hashtable.s"
	@echo "... src/hostlist.o"
	@echo "... src/hostlist.i"
	@echo "... src/hostlist.s"
	@echo "... src/http/http.o"
	@echo "... src/http/http.i"
	@echo "... src/http/http.s"
	@echo "... src/http/http_io.o"
	@echo "... src/http/http_io.i"
	@echo "... src/http/http_io.s"
	@echo "... src/instance.o"
	@echo "... src/instance.i"
	@echo "... src/instance.s"
	@echo "... src/iofactory.o"
	@echo "... src/iofactory.i"
	@echo "... src/iofactory.s"
	@echo "... src/jsparse/parser.o"
	@echo "... src/jsparse/parser.i"
	@echo "... src/jsparse/parser.s"
	@echo "... src/lcbht/lcbht.o"
	@echo "... src/lcbht/lcbht.i"
	@echo "... src/lcbht/lcbht.s"
	@echo "... src/lcbio/connect.o"
	@echo "... src/lcbio/connect.i"
	@echo "... src/lcbio/connect.s"
	@echo "... src/lcbio/ctx.o"
	@echo "... src/lcbio/ctx.i"
	@echo "... src/lcbio/ctx.s"
	@echo "... src/lcbio/iotable.o"
	@echo "... src/lcbio/iotable.i"
	@echo "... src/lcbio/iotable.s"
	@echo "... src/lcbio/ioutils.o"
	@echo "... src/lcbio/ioutils.i"
	@echo "... src/lcbio/ioutils.s"
	@echo "... src/lcbio/manager.o"
	@echo "... src/lcbio/manager.i"
	@echo "... src/lcbio/manager.s"
	@echo "... src/lcbio/protoctx.o"
	@echo "... src/lcbio/protoctx.i"
	@echo "... src/lcbio/protoctx.s"
	@echo "... src/lcbio/timer.o"
	@echo "... src/lcbio/timer.i"
	@echo "... src/lcbio/timer.s"
	@echo "... src/legacy.o"
	@echo "... src/legacy.i"
	@echo "... src/legacy.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
	@echo "... src/mc/compress.o"
	@echo "... src/mc/compress.i"
	@echo "... src/mc/compress.s"
	@echo "... src/mc/forward.o"
	@echo "... src/mc/forward.i"
	@echo "... src/mc/forward.s"
	@echo "... src/mc/mcreq.o"
	@echo "... src/mc/mcreq.i"
	@echo "... src/mc/mcreq.s"
	@echo "... src/mcserver/mcserver.o"
	@echo "... src/mcserver/mcserver.i"
	@echo "... src/mcserver/mcserver.s"
	@echo "... src/mcserver/negotiate.o"
	@echo "... src/mcserver/negotiate.i"
	@echo "... src/mcserver/negotiate.s"
	@echo "... src/metrics.o"
	@echo "... src/metrics.i"
	@echo "... src/metrics.s"
	@echo "... src/n1ql/ixmgmt.o"
	@echo "... src/n1ql/ixmgmt.i"
	@echo "... src/n1ql/ixmgmt.s"
	@echo "... src/n1ql/n1ql.o"
	@echo "... src/n1ql/n1ql.i"
	@echo "... src/n1ql/n1ql.s"
	@echo "... src/n1ql/params.o"
	@echo "... src/n1ql/params.i"
	@echo "... src/n1ql/params.s"
	@echo "... src/netbuf/netbuf.o"
	@echo "... src/netbuf/netbuf.i"
	@echo "... src/netbuf/netbuf.s"
	@echo "... src/newconfig.o"
	@echo "... src/newconfig.i"
	@echo "... src/newconfig.s"
	@echo "... src/nodeinfo.o"
	@echo "... src/nodeinfo.i"
	@echo "... src/nodeinfo.s"
	@echo "... src/operations/cbflush.o"
	@echo "... src/operations/cbflush.i"
	@echo "... src/operations/cbflush.s"
	@echo "... src/operations/counter.o"
	@echo "... src/operations/counter.i"
	@echo "... src/operations/counter.s"
	@echo "... src/operations/durability-cas.o"
	@echo "... src/operations/durability-cas.i"
	@echo "... src/operations/durability-cas.s"
	@echo "... src/operations/durability-seqno.o"
	@echo "... src/operations/durability-seqno.i"
	@echo "... src/operations/durability-seqno.s"
	@echo "... src/operations/durability.o"
	@echo "... src/operations/durability.i"
	@echo "... src/operations/durability.s"
	@echo "... src/operations/get.o"
	@echo "... src/operations/get.i"
	@echo "... src/operations/get.s"
	@echo "... src/operations/observe-seqno.o"
	@echo "... src/operations/observe-seqno.i"
	@echo "... src/operations/observe-seqno.s"
	@echo "... src/operations/observe.o"
	@echo "... src/operations/observe.i"
	@echo "... src/operations/observe.s"
	@echo "... src/operations/ping.o"
	@echo "... src/operations/ping.i"
	@echo "... src/operations/ping.s"
	@echo "... src/operations/pktfwd.o"
	@echo "... src/operations/pktfwd.i"
	@echo "... src/operations/pktfwd.s"
	@echo "... src/operations/remove.o"
	@echo "... src/operations/remove.i"
	@echo "... src/operations/remove.s"
	@echo "... src/operations/stats.o"
	@echo "... src/operations/stats.i"
	@echo "... src/operations/stats.s"
	@echo "... src/operations/store.o"
	@echo "... src/operations/store.i"
	@echo "... src/operations/store.s"
	@echo "... src/operations/subdoc.o"
	@echo "... src/operations/subdoc.i"
	@echo "... src/operations/subdoc.s"
	@echo "... src/operations/touch.o"
	@echo "... src/operations/touch.i"
	@echo "... src/operations/touch.s"
	@echo "... src/rdb/bigalloc.o"
	@echo "... src/rdb/bigalloc.i"
	@echo "... src/rdb/bigalloc.s"
	@echo "... src/rdb/chunkalloc.o"
	@echo "... src/rdb/chunkalloc.i"
	@echo "... src/rdb/chunkalloc.s"
	@echo "... src/rdb/libcalloc.o"
	@echo "... src/rdb/libcalloc.i"
	@echo "... src/rdb/libcalloc.s"
	@echo "... src/rdb/rope.o"
	@echo "... src/rdb/rope.i"
	@echo "... src/rdb/rope.s"
	@echo "... src/retrychk.o"
	@echo "... src/retrychk.i"
	@echo "... src/retrychk.s"
	@echo "... src/retryq.o"
	@echo "... src/retryq.i"
	@echo "... src/retryq.s"
	@echo "... src/ringbuffer.o"
	@echo "... src/ringbuffer.i"
	@echo "... src/ringbuffer.s"
	@echo "... src/rnd.o"
	@echo "... src/rnd.i"
	@echo "... src/rnd.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/strcodecs/base64.o"
	@echo "... src/strcodecs/base64.i"
	@echo "... src/strcodecs/base64.s"
	@echo "... src/timings.o"
	@echo "... src/timings.i"
	@echo "... src/timings.s"
	@echo "... src/tracing/span.o"
	@echo "... src/tracing/span.i"
	@echo "... src/tracing/span.s"
	@echo "... src/tracing/threshold_logging_tracer.o"
	@echo "... src/tracing/threshold_logging_tracer.i"
	@echo "... src/tracing/threshold_logging_tracer.s"
	@echo "... src/tracing/tracer.o"
	@echo "... src/tracing/tracer.i"
	@echo "... src/tracing/tracer.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
	@echo "... src/views/docreq.o"
	@echo "... src/views/docreq.i"
	@echo "... src/views/docreq.s"
	@echo "... src/views/viewreq.o"
	@echo "... src/views/viewreq.i"
	@echo "... src/views/viewreq.s"
	@echo "... src/wait.o"
	@echo "... src/wait.i"
	@echo "... src/wait.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

