# CMake generated Testfile for 
# Source directory: /home/predator/Documents/Project/temp/libcouchbase/tests
# Build directory: /home/predator/Documents/Project/temp/libcouchbase/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BUILD-TESTS "/usr/bin/cmake" "--build" "/home/predator/Documents/Project/temp/libcouchbase" "--target" "alltests")
add_test(check-select-nonio-tests "/home/predator/Documents/Project/temp/libcouchbase/bin/check-all" "--srcdir" "/home/predator/Documents/Project/temp/libcouchbase" "--testdir" "/home/predator/Documents/Project/temp/libcouchbase/bin" "--libdir" "/home/predator/Documents/Project/temp/libcouchbase/lib" "--plugins" "select" "--tests" "nonio-tests" "--verbose" "--" "--gtest_print_time=1" "--gtest_output=xml:\"/home/predator/Documents/Project/temp/libcouchbase/REPORT_select_nonio-tests.xml\"")
add_test(check-select-rdb-tests "/home/predator/Documents/Project/temp/libcouchbase/bin/check-all" "--srcdir" "/home/predator/Documents/Project/temp/libcouchbase" "--testdir" "/home/predator/Documents/Project/temp/libcouchbase/bin" "--libdir" "/home/predator/Documents/Project/temp/libcouchbase/lib" "--plugins" "select" "--tests" "rdb-tests" "--verbose" "--" "--gtest_print_time=1" "--gtest_output=xml:\"/home/predator/Documents/Project/temp/libcouchbase/REPORT_select_rdb-tests.xml\"")
add_test(check-select-vbucket-tests "/home/predator/Documents/Project/temp/libcouchbase/bin/check-all" "--srcdir" "/home/predator/Documents/Project/temp/libcouchbase" "--testdir" "/home/predator/Documents/Project/temp/libcouchbase/bin" "--libdir" "/home/predator/Documents/Project/temp/libcouchbase/lib" "--plugins" "select" "--tests" "vbucket-tests" "--verbose" "--" "--gtest_print_time=1" "--gtest_output=xml:\"/home/predator/Documents/Project/temp/libcouchbase/REPORT_select_vbucket-tests.xml\"")
add_test(check-select-mc-tests "/home/predator/Documents/Project/temp/libcouchbase/bin/check-all" "--srcdir" "/home/predator/Documents/Project/temp/libcouchbase" "--testdir" "/home/predator/Documents/Project/temp/libcouchbase/bin" "--libdir" "/home/predator/Documents/Project/temp/libcouchbase/lib" "--plugins" "select" "--tests" "mc-tests" "--verbose" "--" "--gtest_print_time=1" "--gtest_output=xml:\"/home/predator/Documents/Project/temp/libcouchbase/REPORT_select_mc-tests.xml\"")
add_test(check-select-htparse-tests "/home/predator/Documents/Project/temp/libcouchbase/bin/check-all" "--srcdir" "/home/predator/Documents/Project/temp/libcouchbase" "--testdir" "/home/predator/Documents/Project/temp/libcouchbase/bin" "--libdir" "/home/predator/Documents/Project/temp/libcouchbase/lib" "--plugins" "select" "--tests" "htparse-tests" "--verbose" "--" "--gtest_print_time=1" "--gtest_output=xml:\"/home/predator/Documents/Project/temp/libcouchbase/REPORT_select_htparse-tests.xml\"")
add_test(check-select-unit-tests "/home/predator/Documents/Project/temp/libcouchbase/bin/check-all" "--srcdir" "/home/predator/Documents/Project/temp/libcouchbase" "--testdir" "/home/predator/Documents/Project/temp/libcouchbase/bin" "--libdir" "/home/predator/Documents/Project/temp/libcouchbase/lib" "--plugins" "select" "--tests" "unit-tests" "--verbose" "--" "--gtest_print_time=1" "--gtest_output=xml:\"/home/predator/Documents/Project/temp/libcouchbase/REPORT_select_unit-tests.xml\"")
add_test(check-select-sock-tests "/home/predator/Documents/Project/temp/libcouchbase/bin/check-all" "--srcdir" "/home/predator/Documents/Project/temp/libcouchbase" "--testdir" "/home/predator/Documents/Project/temp/libcouchbase/bin" "--libdir" "/home/predator/Documents/Project/temp/libcouchbase/lib" "--plugins" "select" "--tests" "sock-tests" "--verbose" "--" "--gtest_print_time=1" "--gtest_output=xml:\"/home/predator/Documents/Project/temp/libcouchbase/REPORT_select_sock-tests.xml\"")
subdirs(gtest)
